version: "3.8"

name: littlebox-strapi-backend-base

services:
  mariadb:
    image: mariadb:latest
    container_name: strapi_mariadb_base
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: strapi
    ports:
      - "3306:3306"
    volumes:
      - strapi_mariadb_data:/var/lib/mysql
      - ../database/db-base.sql:/docker-entrypoint-initdb.d/db-base.sql:ro
    networks:
      - strapi_mariadb_network

volumes:
  strapi_mariadb_data:
    driver: local

networks:
  strapi_mariadb_network:
    driver: bridge
